name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake
        with:
          github_user_name: kimmito
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snk/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/snk/
          keep_files: true
